---
# Exercise for setting up a web server in an EC
- name: Exercise for setting up a web server in an EC
  # hosts: ubuntu
  # Use the public IP if the VM is already created
  hosts: ec2-54-160-203-59.compute-1.amazonaws.com
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  roles:
    - setup
