# Exercise: Config and Deployment
version: 2.1
configure_infrastructure:
  docker:
    - image: python:3.7-alpine3.11
  steps:
    - checkout
    - add_ssh_keys:
        fingerprints:
          - "13:25:bc:d5:59:4c:ef:4d:f5:d5:f5:9f:da:5b:ba:9f"
    - run:
        name: Install Ansible
        command: apk add --update ansible
    - run:
        name: Run Playbook and Configure server
        command: ansible-playbook -i inventory.txt main4.yml
